name: autoreneraku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  pull_request:
    branches: 
      - v*
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ matrix.smalltalk }}
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
    strategy:
      matrix:
        smalltalk: [ Pharo64-12  ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }} .smalltalk-autoreneraku.ston
        shell: bash
        timeout-minutes: 15
      - name: AutoReneraku
        uses: badetitou/AutoReneraku@main
        with:
          pat: ${{ secrets.PAT }}
          smalltalk: ${{ steps.smalltalkci.outputs.smalltalk-image }}
          pharo-image: '/home/runner/.smalltalkCI/_builds/TravisCI.image'